import next from "eslint-config-next";

// `eslint-config-next` default-exports a flat-config array, not a factory.
export default [
  ...next,
  {
    ignores: [
      ".next/**",
      ".tmp/**",
      // Generated by `wrangler types`, ~10k lines of runtime declarations.
      "worker/worker-configuration.d.ts",
    ],
  },
];
