import "server-only";

import { createHash } from "node:crypto";

/**
 * The end-of-academy voucher code.
 *
 * Derived, never stored. Two properties matter and both fall out of that:
 *
 * - **Stable.** The same joinee sees the same code on every render, after a
 *   re-sync, on the passport and on the day board, and the team leader reads the
 *   same string off the admin desk. A generated-and-stored code would have to
 *   travel through the client-push progress schema, which is the one part of
 *   this codebase with a history of silently rejecting whole uploads over a
 *   single new field - three separate incidents, all documented in
 *   `docs/pre-deploy.md`. Deriving it touches none of that.
 * - **Unguessable.** The seed is `profiles.id`, a v4 UUID that is generated by
 *   the database and never leaves the server: it is not in any API response, any
 *   cookie, or any client bundle. So a joinee cannot compute their own code
 *   early, and cannot compute anybody else's at all.
 *
 * `node:crypto` is fine here: nothing in this app sets
 * `export const runtime = "edge"`, so route handlers and server components run
 * on Node. If that ever changes, swap in Web Crypto - but note `subtle.digest`
 * is async, so the callers would need to become async with it.
 */

/**
 * Crockford base32 minus the letters that get misread aloud - no I, L, O or U.
 * The code gets read down a phone or across a desk to a team leader, so "was
 * that a one or an I" is a real failure mode, not a theoretical one.
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/** Characters of real entropy. 12 over a 32-letter alphabet is 60 bits. */
const LENGTH = 12;

const PREFIX = "ATLYS";

/**
 * Versioned so a future decision to re-issue every code is one character.
 * Changing it invalidates every code already handed out, which is the point.
 */
const SALT = "atlys-academy-voucher:v1:";

/**
 * The voucher code for one profile. Pure and deterministic.
 *
 * Formatted in groups of four (`ATLYS-XXXX-XXXX-XXXX`) because that is how
 * people read a code back without losing their place.
 */
export function voucherCodeFor(profileId: string): string {
  const digest = createHash("sha256").update(SALT + profileId).digest();

  let body = "";
  for (let i = 0; i < LENGTH; i += 1) {
    // One byte per character, reduced into the alphabet. The modulo bias over
    // 256 into 32 is nil - 32 divides 256 exactly.
    body += ALPHABET[digest[i] % ALPHABET.length];
  }

  const groups = body.match(/.{1,4}/g) ?? [body];
  return [PREFIX, ...groups].join("-");
}
